version: "3.9"

services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: shiptracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  ml-service:
    build: ./ml-service
    ports:
      - "8001:8001"

volumes:
  pgdata:
