backend:
  build: ./backend
  ports:
    - "8000:8000"
  volumes:
    - ./backend:/app
  depends_on:
    - db
    - ml-service
  command: >
    sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
